# Generated by Django 5.1.5 on 2025-01-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('wedding', 'Bodas'), ('newborn', 'Recién Nacidos'), ('portrait', 'Retratos'), ('artistic', 'Artístico')], max_length=50),
        ),
    ]
